# Numpy Array  
For complete documentation about Numpy, see https://docs.scipy.org/doc/. 

First, import Numpy Package.  
By convention, most of people assign `np` as alias name 

In [3]:
import numpy as np

Here, we first create list of integer.  
Then, convert it to numpy array.  

In [5]:
x = [1,2,3,-9999,5]
nx = np.array(x)
nx

array([    1,     2,     3, -9999,     5])

In [8]:
y = [10,20,30,40,-9999]
ny = np.array(y)
ny

array([   10,    20,    30,    40, -9999])

We wan arithmetic calcululation, element-wise.   
I.e., `z[i] = x[i] + y[i]` , etc. 

In [10]:
z = nx + ny
z

array([   11,    22,    33, -9959, -9994])

In [12]:
z = nx - ny
z

array([    -9,    -18,    -27, -10039,  10004])

In [14]:
z = nx * ny
z

array([     10,      40,      90, -399960,  -49995])

In [16]:
z = nx / ny
z

array([ 1.00000000e-01,  1.00000000e-01,  1.00000000e-01, -2.49975000e+02,
       -5.00050005e-04])

Suppose, the value `-9999` was (somehow) absent value given from input data.   
We want to replace it to formal representation of "not a number", which is `np.nan`.  
To do so, Numpy array must be array of float (instead of array of integer).   
Unfortunately, we do not have formal representation of integer absent value.  

In [20]:
nx = np.array(x, dtype=float)
ny = np.array(y, dtype=float)
nx, ny

(array([ 1.000e+00,  2.000e+00,  3.000e+00, -9.999e+03,  5.000e+00]),
 array([   10.,    20.,    30.,    40., -9999.]))

In [23]:
nx[nx==-9999] = np.nan
ny[ny==-9999] = np.nan
nx, ny

(array([ 1.,  2.,  3., nan,  5.]), array([10., 20., 30., 40., nan]))

Once formal `np.nan` is included in Numpy array, then arithmetic calculation results `np.nan` when any input is `np.nan`.   
This prevents generating non-sense output by using `nan` in input.   

In [25]:
nx + ny 

array([11., 22., 33., nan, nan])

In [27]:
nx - ny 

array([ -9., -18., -27.,  nan,  nan])

In [29]:
nx * ny

array([10., 40., 90., nan, nan])

In [31]:
nx / ny

array([0.1, 0.1, 0.1, nan, nan])

`sum()` is also underfined with array having any `nan` in it.   So is `mean()`, too. 

In [47]:
nx.sum(), np.sum(ny)

(nan, nan)

In [48]:
nx.mean(), np.mean(ny)

(nan, nan)

**NOTE** `max()` and `min()` generates error when array includes `nan`. 

In [50]:
nx.max()

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)


nan

Suppose, for some reason, `nan` in calculated result must be converted back to the original *input value rule* (i.e., -9999 in this case).  

In [53]:
z = nx + ny
z

array([11., 22., 33., nan, nan])

In [54]:
z[z==np.nan]=-9999
z

array([11., 22., 33., nan, nan])

What's wrong?  
Well, `nan` is invalid to any arithmetic operation including `==`.  
There is a special function, `np.isnan()` to judge if value is `nan` or not.  

In [56]:
z[np.isnan(z)]=-9999
z

array([   11.,    22.,    33., -9999., -9999.])

Suppose, you want to check if there is any `nan` in Numpy array `nx`.  
`np.isnan(nx)` returns an array of boolean value (True/False).  

In [58]:
np.isnan(nx)

array([False, False, False,  True, False])

In python, True=1 and False=0.  Therefore, we simply calcluate `sum` and check if the summed value is zero or not.  

In [60]:
if sum(np.isnan(nx))==0:
    print('No Absent Value')
else:
    print('There is absent Value')

There is absent Value
