# Python List Manipulation

Here is a note on simple list manipulation in Paython3. 

## List Comprehension
Create test data.  
Note that both `x` and `y` are integer

In [2]:
x = [1,2,3,4,5]
y = [10,20,30,40,50]

We want to get `z=x+y`.  
Of course, we can use NumPy, but here we don't intentionally. 
`zip` provides so called `iterator`, which privides a pair of `x[i], y[i]` in each step of iteration. 
The following is therefore calculate `x[i]+y[i]` for each element of `x` and `y`. 

In [4]:
z = [x+y for x,y in zip(x,y)]
z

[11, 22, 33, 44, 55]

We want a list of `[x[i],y[i]]` list.   
Same technique as above can be used. 

In [6]:
z = [[x,y] for x,y in zip(x,y)]
z

[[1, 10], [2, 20], [3, 30], [4, 40], [5, 50]]

## Operator + and *

Common mistake (especially MATLAB user) is as follows.   
Plain Python list supports operator `+,*` but in different way than you might thought.   
For arithmetic operation, we need to use NumPy.  

In [11]:
z = x * 2
z

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [13]:
z = x + y 
z

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

## Slicing  
Slicing is **aliasing** a subset of array.   
Let's recreate new data for demonstration. 

In [3]:
# Create [0,1,2,3,....10] as numpy array
x1 = np.arange(0,11)  
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Slice for the first 3 elements. Here [:3] is from [0] to "one before [3]", i.e., to [2]
x1[:3]

array([0, 1, 2])

In [9]:
# Slice from 2nd ([1]) to 4th ([3])
x1[1:4]

array([1, 2, 3])

In [11]:
# Slice from first ([0]) to end, every 2nd (skip every other element)
x1[::2]

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# Slice in reverse order. Start from [-1], every -1
x1[-1::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

What I mean by **aliasing** is as follows.   
Note that original data has changed.   

In [18]:
x2 = x1[2:4]
print(x1, ':', x2)

# change value in slice
x2[0] = 100 
print(x1, ':', x2)

[  0   1 100   3   4   5   6   7   8   9  10] : [100   3]
[  0   1 100   3   4   5   6   7   8   9  10] : [100   3]


If **alias** is not desired, create **copy** explicitly as follows. 

In [21]:

x3 = x1[2:4].copy()
print(x1, ':', x3)  

x3[0] = 2000
print(x1, ':', x3)  # Note x1 is not modified

[  0   1 100   3   4   5   6   7   8   9  10] : [100   3]
[  0   1 100   3   4   5   6   7   8   9  10] : [2000    3]
