# Basic functions

In [2]:
import numpy as np

## Index Trick

In [19]:
a = np.concatenate(( [3], [0]*5, [100]))
print(a)

# Use np.r[x,y,z] to concatenate 1D vector as one-row array
a = np.r_[3,[0]*5,[100]]
print(a)

# Generating 1D vector
print(np.mgrid[0:4])
print(np.arange(0,4))

# Generating 2D vector 
print(np.mgrid[0:4,0:4][0])  #  to each row (duplicated columns)
print(np.mgrid[0:4,0:4][1])  #  to each col (duplicated row)


[  3   0   0   0   0   0 100]
[  3   0   0   0   0   0 100]
[0 1 2 3]
[0 1 2 3]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


## Polynomials

In [30]:
# Example of f(x) = 3x^2+4x+5
from numpy import poly1d
p = poly1d([3,4,5])
print(p)

# {f(x)}^2
print(p*p)

# integrate f(x) with const = 6
print(p.integ(k=6))

# derivertive of f(x)
print(p.deriv())

# use polynomial for concrete x values 
x = [4,5]
print(p(x))

   2
3 x + 4 x + 5
   4      3      2
9 x + 24 x + 46 x + 40 x + 25
   3     2
1 x + 2 x + 5 x + 6
 
6 x + 4
[ 69 100]


## Vectorizing Functions 
Define function to process one element (e.g., a pair of element from 2 arrays).   
Instead of writing loop to call the function, ***vectorize*** the function. 

In [39]:
def addOrSub(a,b):
    if a>b:
        return a-b
    else:
        return b-a
    
vec_addOrSub = np.vectorize(addOrSub)
a = np.array([0,5,2,5,4])
b = np.array([3,2,4,2,4])
print(vec_addOrSub(a,b))

# same as abs(a-b) in this particular case
print(np.abs(a-b))

[3 3 2 3 0]
[3 3 2 3 0]


## Type Handling
- Array of complex 
- Array or Scalar 
- Type casting (_Not understand well yet!_)

In [46]:
a = np.array([1+10j,2+20j,3])

print(np.iscomplex(a))   # return array of boolean, one to each element
print(np.iscomplexobj(a)) # return true if any element is comples

print(np.real(a))    # real part 
print(np.imag(a))    # imag part

[ True  True False]
True
[ 1.  2.  3.]
[ 10.  20.   0.]


In [56]:
a = np.array([1,2,3])
print(np.isscalar(a))
print(np.isscalar(a[0]))

False
True


In [59]:
np.cast['f'](np.pi)

array(3.1415927410125732, dtype=float32)

In [64]:
np.float32([np.pi])

array([ 3.14159274], dtype=float32)

In [66]:
np.pi

3.141592653589793

## Other useful functions  
These are written in scipy tutorial, but they belong to numpy as document-wise.   
- angle / unwrap
- linspace / logspace 
- select
- factorial / comb

factorial & comb are in scipy.speical subpackage.    
scipy.misc also contains the same but dupreted.  
Others are under numpy package. 

In [74]:
a = [1, 1+1j, 1j]
print(np.angle(a))
print(np.angle(a)/np.pi*180)

b = [1, 1j, -1, -1j, 1, 1j, -1, -1j, 1]
print(np.unwrap(np.angle(b))/np.pi*180)

[ 0.          0.78539816  1.57079633]
[  0.  45.  90.]
[   0.   90.  180.  270.  360.  450.  540.  630.  720.]


In [87]:
# linspace(start,stop,num,endpoint=True,retstep=False,dtype=None)
a = np.linspace(1.5, 2.5, 5)
print(a)

# logspace(start,stop, num, endpoint=True, base=10.0, dtype=None)
b = np.logspace(0, 3, 5)  # from 10^0,  to 10^3
print(b)

[ 1.5   1.75  2.    2.25  2.5 ]
[    1.             5.62341325    31.6227766    177.827941    1000.        ]


In [92]:
# select(condist, choiselist, default=0)
# condist : list of bool array. Length=N of each list element. Mutiple select criterias as array of bool 
# choiselist: list of array.  
condlist = [[True,False], [False,True]]
choiselist = np.array([[1,2],[3,4]])
print(np.select(condlist,choiselist))

a = np.array([1,2,3,4,5])
condlist = [a<3, a>=4]
choiselist = [a, a*a]
print(np.select(condlist,choiselist))

[1 4]
[ 1  2  0 16 25]


In [100]:
from scipy.special import factorial # here factorial and comb exist
# n! = n*(n-1)*..*1
print(factorial(3))

6.0


In [129]:
from scipy.special import comb
print(comb(5,2))  # 5C2 = 5!/(2!*3!)
print(factorial(5)/(factorial(2)*factorial(5-2)))

10.0
10.0
