# File IO (scipy.io)  

From [Scipy.org Tutorial File IO page](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html).


## MATLAB files

In [2]:
import numpy as np
import scipy.io as sio

In [20]:
# Save array (name='var') in MAT file
# 2nd parameter to savemat() is dictionary ('name':variable)
vect = np.arange(10)
print(vect.shape)
matx = np.arange(9.).reshape((3,3));
print(matx.shape)

sio.savemat('./np_vector.mat', {'vect':vect, 'matx':matx})

(10,)
(3, 3)


In [14]:
# Inspect content of MAT file
sio.whosmat('./np_vector.mat')

[('vect', (1, 10), 'int64'), ('matx', (3, 3), 'double')]

In [28]:
# Load data from MAT file 
mat_contents = sio.loadmat('./np_vector.mat')
vect2 = mat_contents['vect']
matx2 = mat_contents['matx']
print(vect2, vect2.shape)
print(matx2, matx2.shape)

# Interesting. 
# 1D array is restored as (1,10)
# To restore the identical shape as original, squeeze() can be used
vect2 = np.squeeze(vect2)
print(vect2.shape)

# squeeze_me=True is convenient option
mat_contents = sio.loadmat('./np_vector.mat', squeeze_me=True)
vect2 = mat_contents['vect']
matx2 = mat_contents['matx']
print(vect2, vect2.shape)
print(matx2, matx2.shape)

[[0 1 2 3 4 5 6 7 8 9]] (1, 10)
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] (3, 3)
(10,)
[0 1 2 3 4 5 6 7 8 9] (10,)
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] (3, 3)


## MATLAB structs

In [32]:
x = np.array([
     ('Rex',  9, 81.0),
     ('Fido', 3, 27.0)], 
    dtype=[
     ('name', 'U10'),   # field 1: name and dtype
     ('age',  'i4'),    # field 2: name and dtype
     ('weight', 'f4')   # field 3: name and dtype
    ]
)
print(x)

[('Rex', 9,  81.) ('Fido', 3,  27.)]


In [37]:
sio.savemat('./np_struct.mat', {'x':x})
sio.whosmat('./np_struct.mat')

[('x', (1, 2), 'struct')]

In [42]:
mat_contents = sio.loadmat('./np_struct.mat', squeeze_me=True)
x2 = mat_contents['x']
print(x)

[('Rex', 9,  81.) ('Fido', 3,  27.)]


## MATLAB cell array  
MATLAB cell array is array of object in scipy.

In [46]:
obj_array = np.zeros((2,), dtype=np.object)
obj_array[0] = 1
obj_array[1] = 'a string'
print(obj_array)
sio.savemat('./np_cellarray.mat', {'obj_array':obj_array})

[1 'a string']


In [48]:
sio.whosmat('./np_cellarray.mat')

[('obj_array', (1, 2), 'cell')]

In [51]:
mat_contents = sio.loadmat('./np_cellarray.mat', squeeze_me=True)
obj2 = mat_contents['obj_array']
print(obj2)

[1 'a string']
