# Basic Array Creation and Properties

[nympy quickstart](https://docs.scipy.org/doc/numpy/user/quickstart.html)

In [239]:
import numpy as np

# --- Basic Array Attributes ---
#0 to 14 linear vector
a1 = np.arange(15)
print('a=', a1)

# 3 rows x 5 columns 2D array
a2 = a1.reshape(3,5)
print('a2=',a2)
print('a2.ndim=', a2.ndim)
print('a2.shape=', a2.shape)
print('a2.dtype = ', a2.dtype, a2.dtype.name)
print('a2.itemsize = ', a2.itemsize)  # 8 bytes 
print('a2.size = ', a2.size)
print('type(a2) = ', type(a2))

a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a2= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a2.ndim= 2
a2.shape= (3, 5)
a2.dtype =  int64 int64
a2.itemsize =  8
a2.size =  15
type(a2) =  <class 'numpy.ndarray'>


In [240]:
# --- Array creation ---
b1 = np.array([6,7,8])
print('== Elements all integer')
print(b1)
print(b1.dtype)

b2 = np.array([1.1, 1,2, 1,3])
print('== Elements with float')
print(b2)
print(b2.dtype)

b3 = np.array([100,101,102], dtype='float64')
print('== Explicitly float64')
print(b3)
print(b3.dtype)

c1 = np.array([ [1,2,3], [4,5,6]], dtype=complex)
print('== Explicitly complex')
print(c1)
print(c1.dtype)

c2 = np.array([ [1+2j, 2+3j, 3+4j], [4+5j, 5+6j, 6+7j] ])
print('== Implicitly complex')
print(c2)
print(c2.dtype)

== Elements all integer
[6 7 8]
int64
== Elements with float
[ 1.1  1.   2.   1.   3. ]
float64
== Explicitly float64
[ 100.  101.  102.]
float64
== Explicitly complex
[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j]]
complex128
== Implicitly complex
[[ 1.+2.j  2.+3.j  3.+4.j]
 [ 4.+5.j  5.+6.j  6.+7.j]]
complex128


In [241]:
# --- Array creation by functions 
z = np.zeros( (3,4) )
print('=== 3x4 2D array with zeros')
print(z)
print(z.shape)
print(z.dtype)

o = np.ones( (2,3) )
print('=== 2x3 2D array with ones')
print(o)
print(o.shape)
print(o.dtype)

u = np.empty( (3,2) )
print('=== 3x2 2D array uninitialized')
print(u)
print(u.shape)
print(u.dtype)

x = np.arange(6)
print('=== arange(6) = 0:1:(6-1)')
print(x)
print(x.dtype)

x = np.arange(1,10,1) # 'until' is exclusive
print('=== arange(from,until,step) = 1:1:(10-1)')
print(x)
print(x.dtype)

x = np.arange(1,10,1, dtype=np.float64)
print('=== arange(from,until,step) specifically in float64')
print(x)
print(x.dtype)

x = np.linspace(0,10,11) # to is inclusive 
print('=== linspace(from,to,num)')
print(x)

x = np.random.random(5)
print('=== Random 1D')
print(x)

x = np.random.random((2,3))
print('== Random 2D (2x3)')
print(x)

def f(x,y):
    return 10*x+y

x = np.fromfunction(f, (2,3), dtype=int)
print('=== fromfunction 2D(2x3) : 10*(row-index)+(column-index)')
print(x)

=== 3x4 2D array with zeros
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
(3, 4)
float64
=== 2x3 2D array with ones
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
(2, 3)
float64
=== 3x2 2D array uninitialized
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
(3, 2)
float64
=== arange(6) = 0:1:(6-1)
[0 1 2 3 4 5]
int64
=== arange(from,until,step) = 1:1:(10-1)
[1 2 3 4 5 6 7 8 9]
int64
=== arange(from,until,step) specifically in float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
float64
=== linspace(from,to,num)
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
=== Random 1D
[ 0.86505096  0.85113895  0.72525577  0.38221341  0.50873387]
== Random 2D (2x3)
[[ 0.78755545  0.99048749  0.50347471]
 [ 0.58259523  0.54842836  0.93545754]]
=== fromfunction 2D(2x3) : 10*(row-index)+(column-index)
[[ 0  1  2]
 [10 11 12]]


# Array shape operation

In [242]:
# --- Array shape 
a1 = np.array([1,2,3,4,5,6])
a2 = a1.reshape(3,2)
print('=== Reshape 1x6 to 3x3')
print('shape=',a1.shape, 'val=\n', a1)
print('shape=',a2.shape, 'val=\n', a2)

# --- Flattern
print('=== Flattern to 1D array')
a3 = a2.ravel()
print('ravel() =',a3)
a3 = np.array(a2.flat);
print('flat =', a3)  # same result

#--- 3x2 to 2x3
a4 = a2.reshape(2,-1); # -1 to resolve automatically 
print('=== Using -1 to recompute remaining dim')
print(a4)

=== Reshape 1x6 to 3x3
shape= (6,) val=
 [1 2 3 4 5 6]
shape= (3, 2) val=
 [[1 2]
 [3 4]
 [5 6]]
=== Flattern to 1D array
ravel() = [1 2 3 4 5 6]
flat = [1 2 3 4 5 6]
=== Using -1 to recompute remaining dim
[[1 2 3]
 [4 5 6]]


In [243]:
# --- Stacking array
a = np.array([[1,2],[3,4]])
b = np.array([[101,102],[103,104]])
c = np.vstack((a,b))
print('=== Stacking 2D array vertically')
print(c)

c = np.hstack((a,b))
print('=== Stacking 2D array horizontally')
print(c)

c = np.column_stack((a,b))
print('=== Column stack of 2D array')
print(c)

aa = np.array([1,2,3,4,5]);
bb = np.array([11,12,13,14,15])
cc = np.column_stack((aa,bb))
print('=== Column stack of 1D array')
print(cc)

aaa = np.c_[aa, bb]
print('=== Column stack in different notation')
print(aaa)

aaa = np.hstack( (aa, bb) )
print('=== Append to 1D array')
print(aaa)


aaa = np.r_[aa,bb]
print('=== Raw stack in different notation')
print(aaa)


=== Stacking 2D array vertically
[[  1   2]
 [  3   4]
 [101 102]
 [103 104]]
=== Stacking 2D array horizontally
[[  1   2 101 102]
 [  3   4 103 104]]
=== Column stack of 2D array
[[  1   2 101 102]
 [  3   4 103 104]]
=== Column stack of 1D array
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]
=== Column stack in different notation
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]
=== Append to 1D array
[ 1  2  3  4  5 11 12 13 14 15]
=== Raw stack in different notation
[ 1  2  3  4  5 11 12 13 14 15]


In [244]:
# --- Splitting array into smaller one 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
aa = np.hsplit(a,3);
print('=== Horizontal split ')
print(aa)

aa = np.vsplit(a,3)
print('=== Vertical split ')
print(aa)


=== Horizontal split 
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
=== Vertical split 
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


# Basic Arithmetic

In [245]:
# --- Basic Array Arithmetic Operations 
a = np.array([20,30,40,50])
b = np.arange(4) #[0,1,2,3]

print('=== Element wise add/subtract')
print('a-b=', a-b)
print('a+b=', a+b)

print('=== Element wise product')
print('a.*b=', a*b)

print('=== Matrix product')
print('a*b=', np.dot(a,b))
#print('a*b=',a.dot(b)) #same as above

c = np.linspace(0, 3.14, 10) # 0 to (about) pi 
d = np.exp(c*1j)
print('=== Exponent (complex)')
print('exp(c*1j)=:', d)
print('dtype=:', d.dtype)




=== Element wise add/subtract
a-b= [20 29 38 47]
a+b= [20 31 42 53]
=== Element wise product
a.*b= [  0  30  80 150]
=== Matrix product
a*b= 260
=== Exponent (complex)
exp(c*1j)=: [ 1.00000000+0.j          0.93975313+0.34185385j  0.76627189+0.64251645j
  0.50045969+0.86575984j  0.17434523+0.98468459j -0.17277674+0.98496101j
 -0.49908020+0.8665558j  -0.76524761+0.64373604j -0.93920748+0.34335012j
 -0.99999873+0.00159265j]
dtype=: complex128


In [246]:
# --- Basic Array Arithmetic for Statistics 
a = np.array([[1,2,3],[4,5,6]])
z = a.sum()
print('=== Summation of all elements')
print(z)

z = a.sum(axis=0)
print('=== Summation along 0 axis (along rows, to each column)')
print(z)

z = a.sum(axis=1) 
print('=== Summation along 1 axis (along column, to each row)')
print(z)

print('=== Max/min of all elements')
print('max=', a.max(), ', min=', a.min())

z = a.max(axis=0)
print('=== Max along 0 axis (along rows, to each column)')
print(z)

z = a.max(axis=1)
print('=== Max along 1 axis (along columns, to each row)')
print(z)

z = a.cumsum(axis=1) 
print('=== Cumulative sum along 1 axis (along columns, to each row)')
print(z)

a1 = a.ravel() # flatten
v1 = a1 <= 3
print('=== Array of True/False after value comparison')
print(v1)

=== Summation of all elements
21
=== Summation along 0 axis (along rows, to each column)
[5 7 9]
=== Summation along 1 axis (along column, to each row)
[ 6 15]
=== Max/min of all elements
max= 6 , min= 1
=== Max along 0 axis (along rows, to each column)
[4 5 6]
=== Max along 1 axis (along columns, to each row)
[3 6]
=== Cumulative sum along 1 axis (along columns, to each row)
[[ 1  3  6]
 [ 4  9 15]]
=== Array of True/False after value comparison
[ True  True  True False False False]


In [247]:
# index of maximum 
a = np.array([0,1,2,1,0])
i = a.argmax()
print('=== Index of max of ', a, 'is' ,i)

print('=== Index of max to each column (max among all rows of each column)')
a = np.array([[10,2,30],[2,3,4]])
i = a.argmax(axis=0) 
print(a, '\n------------\n', i)

=== Index of max of  [0 1 2 1 0] is 2
=== Index of max to each column (max among all rows of each column)
[[10  2 30]
 [ 2  3  4]] 
------------
 [0 1 0]


# Linear Algebra (Basic)

In [277]:
a = np.array([[1.0, 2.0],[3.0, 4.0]])
print('=== Input: a=')
print(a)

print('== Transpose: a.transpose()=')
print(a.transpose())

print('== Inverse: np.linalg.inv(a)')
ai = np.linalg.inv(a)
print(ai)
#print(np.dot(a,ai)) ~ almost zero 

print('== Eye matrix 2x2')
u = np.eye(2)
print(u)

print('== Trace is sum along diagonals ')
print(np.trace(u))

print('== solve(a,b) for x where ax = b')
b = np.array([[5.],[7.]])  # a*x = b
print(np.linalg.solve(a,b)) 
print(np.dot(np.linalg.inv(a), b)) # x = inv(a) * b

=== Input: a=
[[ 1.  2.]
 [ 3.  4.]]
== Transpose: a.transpose()=
[[ 1.  3.]
 [ 2.  4.]]
== Inverse: np.linalg.inv(a)
[[-2.   1. ]
 [ 1.5 -0.5]]
== Eye matrix 2x2
[[ 1.  0.]
 [ 0.  1.]]
== Trace is sum along diagonals 
2.0
== solve(a,b) for x where ax = b
[[-3.]
 [ 4.]]
[[-3.]
 [ 4.]]


# Indexing, Slicing

In [248]:
#--- Indexing, Slicing, Iterating 
a = np.arange(10)
print('=== index to 1D array')
print(a[2])

print('=== slicing 1D array')
print(a[3:5]) # from:to(exclusive)

print('=== slicing by negative index (from end)')
print(a[-2:])

print('=== reversing order')
print(a[::-1])

print('=== selecting with step a[from:to:step]')
print(a[0:9:2])

print('=== loop over element in array')
for e in a:
    print(e)
    


=== index to 1D array
2
=== slicing 1D array
[3 4]
=== slicing by negative index (from end)
[8 9]
=== reversing order
[9 8 7 6 5 4 3 2 1 0]
=== selecting with step a[from:to:step]
[0 2 4 6 8]
=== loop over element in array
0
1
2
3
4
5
6
7
8
9


In [249]:
# --- Indexing with slicing 
a = np.array([1,2,3,4,5])
a[2:4] = 0;
print('=== a[2]=a[3]=0')
print(a)

b = a[a>0]
print('=== Extract b=a[a>0] (deep copy)')
print(b)
b[1] = 0
print('Extracted as deep copy','b=', b, 'a=', a)

a[[0,2,4]] += 100
print('=== Operation to a subset of array')
print(a)

=== a[2]=a[3]=0
[1 2 0 0 5]
=== Extract b=a[a>0] (deep copy)
[1 2 5]
Extracted as deep copy b= [1 0 5] a= [1 2 0 0 5]
=== Operation to a subset of array
[101   2 100   0 105]


# Copy and Views

In [250]:
#--- Assignment is shallow copy 
a = np.array([1,2,3,4,5,6])
b = a         # shallow copy 
print('b is a? :', b is a)
a[0] = 0
print('Change to a is also to b, i.e.,', a, b)

bb = a.copy() # deep copy 
print('bb is a? :', bb is a)

a[0] = 100;
print('Change to a is NOT to bb, i.e.,', a, bb)

c = a.view()
c[0]=1
print('Change to view is also change to original', a, c)

c.shape = 3,2
print('Change to shape of view does not propagate to original :', a.shape, c.shape)

c = a[1:3] # slicing is view
c[0] = 102
c[1] = 103
print('Slice = ',c,'Original = ', a)


b is a? : True
Change to a is also to b, i.e., [0 2 3 4 5 6] [0 2 3 4 5 6]
bb is a? : False
Change to a is NOT to bb, i.e., [100   2   3   4   5   6] [0 2 3 4 5 6]
Change to view is also change to original [1 2 3 4 5 6] [1 2 3 4 5 6]
Change to shape of view does not propagate to original : (6,) (3, 2)
Slice =  [102 103] Original =  [  1 102 103   4   5   6]


# Discrete Indexing 

In [251]:
a = np.arange(10) + 100
i = np.array([1,3,5])
print('=== Extract in simple 1D index')
print('a =', a, 'i =', i, 'a[i] = ', a[i])

print('=== Extract in the same shape as index')
i = np.array([ [1,2],[3,4] ])
print(a[i])

=== Extract in simple 1D index
a = [100 101 102 103 104 105 106 107 108 109] i = [1 3 5] a[i] =  [101 103 105]
=== Extract in the same shape as index
[[101 102]
 [103 104]]


# Boolean Indexing 

In [252]:
a = np.array([1,2,3,4,5]);
b = np.array([True,False,True,False,True])
c = a[b]
print('=== Select element only from "True" indexes')
print('a=', a, 'b=', b, 'c=', c)

a = np.array([[1,2,3],[4,5,6]])
b1 = np.array([True, False])
b2 = np.array([False, True, False])
c1 = a[b1,:] # select rows  
c2 = a[:,b2] # select columns 
print('=== With input a=\n', a)
print('=== Select rows by ', b1)
print(c1)

print('=== Select columns by ', b2)
print(c2)

print('=== Select (row,colum) by (b1,b2) ')
print(a[b1,b2])



=== Select element only from "True" indexes
a= [1 2 3 4 5] b= [ True False  True False  True] c= [1 3 5]
=== With input a=
 [[1 2 3]
 [4 5 6]]
=== Select rows by  [ True False]
[[1 2 3]]
=== Select columns by  [False  True False]
[[2]
 [5]]
=== Select (row,colum) by (b1,b2) 
[2]


# Combination Arithmetic by ix_() 

In [264]:
a = np.array([1,2,3])
b = np.array([4,5])
c = np.array([100,101,102])

# Comvert to 3D matrixes with 3 inputs 
ax,bx,cx = np.ix_(a,b,c)
print(ax.shape)
print(bx.shape)
print(cx.shape)

# result in all combination 
result = ax + bx * cx
print(result)

print( 'Each element= ',a[2] + b[1] * c[2] )
print( 'Matrix result=', result[2,1,2] )

(3, 1, 1)
(1, 2, 1)
(1, 1, 3)
[[[401 405 409]
  [501 506 511]]

 [[402 406 410]
  [502 507 512]]

 [[403 407 411]
  [503 508 513]]]
Each element=  513
Matrix result= 513
