# Broadcasting
[Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) is a bit interesting feature of Python. At least, this does not exist in MATLAB.   
When operating on two arrays (e.g., +, *, element-wise operation), the following two cases are manged by ***broadcast rule***.  
- For the dimension one array has, another array does not have corresponding dimension.  
- For the dimension one array has, another array has dimension of 1. 

e.g., Valid combinations
```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```
```
A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

e.g., Invalid combinations 
```
A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

In [2]:
import numpy as np

Here, x and y are in different shape, so broadcast does not work

In [8]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

print('x.shape', x.shape)
print('y.shape', y.shape)

x+y # error (shape mismatch)

x.shape (4,)
y.shape (5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

Here, xx is (4,1).  
y is 1D vector (5,). 
```
xx    4 x 1 
y         5 
res   4 x 5
```

y is extended  to (4,5), hence equivalent to np.ones(4,5)

In [16]:
print('xx=\n', xx)
print('xx.shape', xx.shape)
print('y=\n', y)
print('y.shape', y.shape)
print('xx+y=\n',xx+y)
print('xx+y shape=', (xx+y).shape)


xx=
 [[0]
 [1]
 [2]
 [3]]
xx.shape (4, 1)
y=
 [ 1.  1.  1.  1.  1.]
y.shape (5,)
xx+y=
 [[ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.]]
xx+y shape= (4, 5)


x is 1D vector shape = (4,)
z is 2D vector shape = (3,4) 

```
x       4 
z   3 x 4
res 3 x 4
```

x is extended to 3 rows (additional 2 rows) 

In [20]:
print('x.shape', x.shape)
print('z.shape', z.shape)

print('(x+z).shape', (x+z).shape)
print('x+z=\n', x+z)

x.shape (4,)
z.shape (3, 4)
(x+z).shape (3, 4)
x+z=
 [[ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]]


a.shape = (4,)
a[:,np.newaxis].shape = (4,1)
b.shape = (3,)

```
a[:,np.newaxis]      4 x 1 
b                        3
res                  4 x 3
```
b[] is extended to (4,3) by duplicating 

In [28]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

print("### The following two are equivalent")
print(a[:,np.newaxis], '\n')
print(a.reshape(4,1), '\n')

print(a[:,np.newaxis] + b)

### The following two are equivalent
[[  0.]
 [ 10.]
 [ 20.]
 [ 30.]] 

[[  0.]
 [ 10.]
 [ 20.]
 [ 30.]] 

[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]
