# Indexing 
[Indexing in Numpy manual](https://docs.scipy.org/doc/numpy/user/basics.indexing.html)

## Indexing to array - basic

In [3]:
import numpy as np

x = np.arange(10)
print(x[2])
print(x[-2])

2
8


In [7]:
x.shape=(2,5) # reshape
print(x[0,3])
print(x[1,3])

3
8


In [10]:
print(x[0]) # first row
print(x[1]) # second row

[0 1 2 3 4]
[5 6 7 8 9]


## Slice 

In [19]:
y = np.arange(35).reshape(5,7)
print(y)

# ::3 = from first, to end(inclusinve), every 3
z = y[1:5:2,::3]
print(z)

# 0:-1:3 = from first, to end exclusive(!), every 3
z = y[1:5:2,0:-1:3]
print(z)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]
[[ 7 10]
 [21 24]]


## Index Arrays (array of index)

In [38]:
# 1D array
x = np.arange(10,0,-1)
print('x[:]=', x)
print('x[even]=', x[0::2])
print('x[[1,3,4]]=', x[[1,3,4]])

x[:]= [10  9  8  7  6  5  4  3  2  1]
x[even]= [10  8  6  4  2]
x[[1,3,4]]= [9 7 6]


In [47]:
# Multi-Dimensional 
y = np.arange(35).reshape(5,7)
print('y=\n',y)

# [rows], [columns] pairs for 2D 
yy = y[ [0,2,4], [0,1,2] ]
print('y[0,0],[2,1],[4,2]=', yy)
yy = y[ np.array([0,2,4]), np.array([0,1,2])]
print('ditto           =', yy)
print("\n")

# Common column
yy = y[ np.array([0,2,4]), 1]
print('y[0,1],[2,1],[4,1]=',yy)

# Rows only 
yy = y[ np.array([0,2,4])]
print('y[0/2/4,:] = \n', yy)

y=
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
y[0,0],[2,1],[4,2]= [ 0 15 30]
ditto           = [ 0 15 30]


y[0,1],[2,1],[4,1]= [ 1 15 29]
y[0/2/4,:] = 
 [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]


## Boolean index (or mask index) arrays

In [56]:
y = np.arange(35).reshape(5,7)
print('y=\n',y)

b = y > 20
print('b[]=', b)
print('y[]>20 = ', y[b])

print('b[:,5]=', b[:,5])       # extract 5th column of b[]
print('y[b[:,5]]=', y[b[:,5]]) # extract y[] rows where b[]==True

y=
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
b[]= [[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
y[]>20 =  [21 22 23 24 25 26 27 28 29 30 31 32 33 34]
b[:,5]= [False False False  True  True]
y[b[:,5]]= [[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [62]:
# 3D (2,3,5) 
# selector boolean b(2,3) with 4 true elements 
# results in (4,5) array ... (2,3,x) => (4,x)
x = np.arange(30).reshape(2,3,5)
print('x=\n', x)

b = np.array( [[True, True, False],[False, True, True]])
print('\n')
print('x[b]=\n', x[b])

x=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


x[b]=
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [25 26 27 28 29]]


## Structural indexing tools

In [79]:
x = np.arange(5)
print('x=', x)

print('x[:,np.newaxis]=', x[:,np.newaxis])
print('x[np.newaxis,:]=', x[np.newaxis,:])
print('x[:,np.newaxis]+x[np.newaxis,:]=')
print(x[:,np.newaxis]+x[np.newaxis,:])

x1 = np.array([[0],[1]])
x2 = np.array([[3,4]])
print('x1.shape=', x1.shape)
print('x2.shape=', x2.shape)
print(x1+x2)


x= [0 1 2 3 4]
x[:,np.newaxis]= [[0]
 [1]
 [2]
 [3]
 [4]]
x[np.newaxis,:]= [[0 1 2 3 4]]
x[:,np.newaxis]+x[np.newaxis,:]=
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
x1.shape= (2, 1)
x2.shape= (1, 2)
[[3 4]
 [4 5]]


## Ellipsis syntax

In [83]:
z = np.arange(81).reshape(3,3,3,3)
# ellipsis syntax ....
print(z[1,...,2])

[[29 32 35]
 [38 41 44]
 [47 50 53]]


In [84]:
# same as this 
print(z[1,:,:,2])

[[29 32 35]
 [38 41 44]
 [47 50 53]]


In [97]:
z = np.arange(81).reshape(3,3,3,3)

indices = (1,1,1,1)
print(z[indices])

indices = (1,1,1,slice(0,2))
print(z[indices])
print(z[1,1,1,0:2])


40
[39 40]
[39 40]


## Index by list or tupple 
***NOTE:*** This is not well understood yet !!!

In [120]:
z = np.arange(4).reshape(2,2)
print('::: z =')
print(z)
print('::: z[1,0]=')
print(z[1,0])
print('::: z[[1,0]]= [1st_row, 0th_row]  ???')
print(z[[1,0]])
print('::: z[(1,0)]= same as z[1,0]')
print(z[(1,0)])

::: z =
[[0 1]
 [2 3]]
::: z[1,0]=
2
::: z[[1,0]]= [1st_row, 0th_row]  ???
[[2 3]
 [0 1]]
::: z[(1,0)]= same as z[1,0]
2
