# MATLAB
From [SciPy.org user manual](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html), some fundamental MATLAB operations I'm personally familiar are noted for their Python equivalent.  This is not the complete list. Some operations are in `scipy.linalg`.  FFT related is in `numpy.fft` module.   

Also refers to http://mathesaurus.sourceforge.net/matlab-numpy.html


In [8]:
import numpy as np
import scipy.linalg

>`a && b` => `a and b`

In [4]:
a=True 
b=False
if a and b:
    print('no way')
else:
    print('yap')

yap


>`a || b` ==> `a or b`

In [6]:
a=True 
b=False
if a or b:
    print('yap')
else:
    print('nop')

yap


>`ndims(a) ==> ndim(a) or a.ndim`   # the number of dimension

In [39]:
a = np.array([[1,2,3],[4,5,6]])
print(np.ndim(a))
print(a.ndim)

2
2


>`numel(a) ==> size(a) or a.size`  # the total number of elements in array 

In [36]:
a = np.arange(6).reshape(2,3)
print(np.size(a))
print(a.size)

6
6


>`size(a)`

In [14]:
a = np.array([1,2,3])
print(np.shape(a), a.shape)

(3,) (3,)


>`[1,2,3;4,5,6] => array([1,2,3],[4,5,6])`

In [17]:
a = np.array([ [1,2,3], [4,5,6] ])
print(a)

[[1 2 3]
 [4 5 6]]


>`a(1:5) ==> a[0:5]`  

*** Note about exclusiveness in python. Also, slice is 'view' ***

In [20]:
a = np.arange(10.)
print(a[0:2])

[ 0.  1.]


>`a(1:2:10) ==> a[0:10:2]

In [22]:
a = np.arange(10)
print(a[0:10:2])

[0 2 4 6 8]


>`a(end:-1:1) ==> a[::-1]`   # flippling

In [26]:
a = np.arange(10)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


>`a(end:-1:1, :) ==> a[::-1,:]`  # row flipping (or MATLAB flipud()

In [33]:
a = np.arange(9).reshape((3,3))
print(a)
print(a[::-1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


>`a.' ==> a.transpose() or a.T`     # transpose (without conjugate)

In [45]:
a = np.arange(6).reshape((2,3))
print(a)
print(a.T)
print(a.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


>`a' ==> a.conj().transpose() or a.conj().T`  # transpose with conjugate

In [63]:
a = np.arange(6).reshape((2,3))
b = np.arange(6).reshape((2,3))*1j
c = a+b
print(c)
print(c.conj().T)

[[ 0.+0.j  1.+1.j  2.+2.j]
 [ 3.+3.j  4.+4.j  5.+5.j]]
[[ 0.-0.j  3.-3.j]
 [ 1.-1.j  4.-4.j]
 [ 2.-2.j  5.-5.j]]


>`a * b ==> a.dot(b) or np.dob(a,b)`  
>`a .* b ==> a * b`  
>`a ./ b ==> a / b`  
>`a.^3 ==> a**3`

In [72]:
a = np.arange(6)
b = np.arange(6) + 1
print(a*b)
print(a/b)
print(a**3)

[ 0  2  6 12 20 30]
[ 0.          0.5         0.66666667  0.75        0.8         0.83333333]
[  0   1   8  27  64 125]


>`find(a>0.5) ==> nonzero(a>0.5)`  # return index

In [82]:
a = np.arange(10) / 10
i = np.nonzero(a>0.5)[0]
print(i, '\n', a[i])

[6 7 8 9] 
 [ 0.6  0.7  0.8  0.9]


In [87]:
a = np.arange(9).reshape((3,3))/10.
i = np.nonzero(a>0.5)
print(i)
print(a[i])

(array([2, 2, 2]), array([0, 1, 2]))
[ 0.6  0.7  0.8]


>`a .* (a>0.5) ==> a * (a>0.5)`     # make larger than 0.5 to zero 

In [91]:
a = np.arange(0,1,0.1)
print(a)
print( a * (a>0.5) )

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
[ 0.   0.   0.   0.   0.   0.   0.6  0.7  0.8  0.9]


>`a = b  ==> a = b.copy()`   # ***This is fundamental difference. Array assignment is shallow copy***

In [93]:
a = np.arange(10)
b = a.copy()
b[0] = 100
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


>`repmat(a,m,n) ==> tile(a, (m,n))`   # create (m x n) copies of a

In [100]:
a = np.array([1,2,3])
print(np.tile(a,(2,1)),'\n')
print(np.tile(a,(1,2)), '\n')
print(np.tile(a,(2,2)), '\n')

[[1 2 3]
 [1 2 3]] 

[[1 2 3 1 2 3]] 

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]] 



>`[a b] ==> hstack((a,b))`  
>`[a;b] ==> vstack((a,b))`

In [124]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))
print(np.r_[a,b])  # note: 1D specific
print('\n')
print(np.vstack((a,b)))
print(np.c_[a,b])
print(np.c_[a,b].T) # note: 1D specific

[1 2 3 4 5 6]
[1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [125]:
a = np.arange(6).reshape((2,3))
b = a.copy() + 100
print(np.hstack((a,b)))
print(np.c_[a,b])
print()
print(np.vstack((a,b)))
print(np.r_[a,b])

[[  0   1   2 100 101 102]
 [  3   4   5 103 104 105]]
[[  0   1   2 100 101 102]
 [  3   4   5 103 104 105]]

[[  0   1   2]
 [  3   4   5]
 [100 101 102]
 [103 104 105]]
[[  0   1   2]
 [  3   4   5]
 [100 101 102]
 [103 104 105]]


>`max(max(a)) ==> a.max()`     # Max of 2D matrix

In [127]:
a = np.arange(9).reshape((3,3))
print(a.max())

8


> `max(a) ==> a.max(0)`       # maximum element of each column of 2D matrix : 0 = across rows 
> `max(a,[],2) ==> a.max(1)`  # maximum element of each row of 2D matrix    : 1 = across columns

In [131]:
a = np.arange(9).reshape((3,3))
print(a)
print(a.max(0))
print(a.max(1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
[2 5 8]


> `a & b ==> logical_and(a,b)`   # logical AND  
> `a | b ==> locgical_or(a,b)`   # logical OR 

In [137]:
a = True
b = False
print(np.logical_and(a,b))
print(np.logical_or(a,b))


False
True


> `bitand(a,b) ==> a & b`     # bitwise AND  
> `bitor(a,b)  ==> a | b`     # bitwise OR 

In [141]:
a = 0x5a
b = 0x08
print(a&b)
print(a|b)

8
90


>`inv(a) ==> linalg.inv(a)`     # inverse of square matrix  
>`pinv(a) ==> linalg.pinv(a)`   # peudo-inverse matrix

In [147]:
a = np.eye(3)
print(a)
print(np.linalg.inv(a))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


>`a\b  ==> linalg.solve(a,b)`      # solution of x to a*x = b  (square)

In [182]:
a = np.eye(3)
x0 = np.arange(9.).reshape((3,3))
b = a@x0  # np.dot(a,x0)

x1 = np.linalg.solve(a,b)
print(x1)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]


FFT/IFFT is in numpy.fft module
> `fft(a)  ==> fft(a)`  
> `ifft(a) ==> ifft(a)`

In [194]:
x = np.sin(2*np.pi*100*(np.linspace(0,1,512)));
f = np.fft.fft(x)
xx = np.fft.ifft(f)
print('err=', np.max(x-xx))  # should be almost zero

err= (1.49880108324e-15-1.90068110953e-16j)


>`sort(a) ==>  sort(a) or a.sort()`  
***NOTE*** a.sort() modify contents of a

In [202]:
a = np.arange(10,0,-1)
print(a)
b = np.sort(a)
a.sort()
print(b)
print(a)
 

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


>`unique(a) ==> unique(a)`  
To get index,  `u,i = unique(a, return_indices=True)`  

In [207]:
a = np.array([1,2,3,2,3,1,0]);
x,i = np.unique(a, return_index=True)
print(x,i)

[0 1 2 3] [6 0 1 2]


In [212]:
a = np.array([[1,0,0], [1,0,0], [2,3,4]])
print(np.unique(a, axis=0))  # unique rows

[[1 0 0]
 [2 3 4]]


>`squeeze(a) ==> a.squeeze()`  

In [219]:
a = np.arange(9).reshape((3,3))
b = a[0,:].copy()
print(b, b.shape)    # unlike MATLAB, row by slice does not maintain reduced single-dimension. no need for squeeze

[0 1 2] (3,)


In [224]:
a = np.array([[[0],[1],[2]]])
print(a, a.shape)

b = a.squeeze()
print(b, b.shape)

[[[0]
  [1]
  [2]]] (1, 3, 1)
[0 1 2] (3,)
