# IEEE 754 Floating Point Special Values  
- np.nan, np.isnan(), np.nan_to_num()
- np.inf, np.isinf(), np.isfinite()

In [2]:
import numpy as np

In [4]:
a = np.array([0., 1., 2., np.nan, 3])
print(a)

[  0.   1.   2.  nan   3.]


In [12]:
i = ~np.isnan(a)
b = a[i]
print(i, b)

[ True  True  True False  True] [ 0.  1.  2.  3.]


In [19]:
b = np.nan_to_num(a)  # NaN -> 0
print(b)

[ 0.  1.  2.  0.  3.]


In [22]:
c = np.array([1.0, np.inf, 2.0])
print(c)

[  1.  inf   2.]


In [24]:
i = ~np.isinf(c)
d = c[i]
print(d)

[ 1.  2.]


Function to exclude nans from results.   
When usuan function, e.g., `sum()` is used with array having NaN inside, result is always NaN. 
- namsum() 
- nanmax()
- nanmin()
- nanargmax()
- nanargmin()

In [31]:
x = np.arange(10.)
x[5] = np.nan
print('x.sum()=', x.sum())
print('np.nansum(x)=', np.nansum(x))


x.sum()= nan
np.nansum(x)= 40.0


---
## Interfacing to C, Fortran, C++
*When necessity arises, refer the original reference*  
[Scipy.org user manual](https://docs.scipy.org/doc/numpy/user/misc.html)

## Marix?   
Advantage of matrix is to use `*` operator for tensor multplying.  To array, np.dot (or A.dot(B) must be used. 
From Python 3.5, `@` can be used for tensor multiplying with array type. 

In [51]:
a = np.arange(9).reshape((3,3))+1
b = np.eye(3,3)
b *= 100
print('np.dot(a,b) \n', np.dot(a,b), '\n')
print('a@b\n', a@b, '\n')
print('a*b\n', a*b)

np.dot(a,b) 
 [[ 100.  200.  300.]
 [ 400.  500.  600.]
 [ 700.  800.  900.]] 

a@b
 [[ 100.  200.  300.]
 [ 400.  500.  600.]
 [ 700.  800.  900.]] 

a*b
 [[ 100.    0.    0.]
 [   0.  500.    0.]
 [   0.    0.  900.]]
