In [2]:
import numpy as np

In [4]:
np.__version__

'1.13.3'

In [8]:
ar = np.array([ [1,2,3], [11,12,13] ], np.int32)
print(ar)

[[ 1  2  3]
 [11 12 13]]


In [9]:
ar.dtype

dtype('int32')

In [11]:
mx = np.matrix([[1,2],[3,4]])
mx

matrix([[1, 2],
        [3, 4]])

In [12]:
mx = np.matrix('1 2;3 4')
mx

matrix([[1, 2],
        [3, 4]])

In [15]:
a = np.array([1,2,3,4,5])
print(a[0])
print(a[0:2])
print(a[-2:])

1
[1 2]
[4 5]


In [17]:
print(a*2)

[ 2  4  6  8 10]


In [19]:
b=np.array([11,12,13,14,15])
print(a+b)

[12 14 16 18 20]


In [22]:
# inner product (sum(a[i]*b[i]))
print(a.dot(b))

205


In [27]:
# numpy cross-product 
a = np.array([1,2,3])
b = np.array([4,5,6])
np.cross(a,b)

array([-3,  6, -3])

In [31]:
print(a + 10)
print(np.add(a,10))

[11 12 13]
[11 12 13]


In [35]:
print(a*10)
print(np.multiply(a,10))

[10 20 30]
[10 20 30]


In [42]:
print(a,a.dtype)
print(a/2)
print(a-1.5)

[1 2 3] int64
[ 0.5  1.   1.5]
[-0.5  0.5  1.5]


In [54]:
# Array generation functions
print(np.arange(0,10,2)) # (start,stop,step)
print(np.identity(2))    # unit matrix (2D)
print(np.ones((2,2)))    # fill by one (argument is tuple)
print(np.zeros((2,2)))
print(np.zeros(5))
print(np.linspace(0,10,6)) # (start, end, num) --> step = (10-0)/(6-1) = 2

[0 2 4 6 8]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]
 [ 0.  0.]]
[ 0.  0.  0.  0.  0.]
[  0.   2.   4.   6.   8.  10.]


In [80]:
import math

def rotate_matrix(rad):
    return np.array( [[math.cos(rad),-math.sin(rad)],[math.sin(rad),math.cos(rad)]])

base = np.array([1,0])
print(base)

num=16
print('degree \t result')
for x in range(num+1):
    rad = 2 * math.pi / num * x 
    rot = rotate_matrix(rad)
    deg = 360 / num * x 
    result = np.dot(rot,base)
    print( deg, '\t', result ) 


[1 0]
degree 	 result
0.0 	 [ 1.  0.]
22.5 	 [ 0.92387953  0.38268343]
45.0 	 [ 0.70710678  0.70710678]
67.5 	 [ 0.38268343  0.92387953]
90.0 	 [  6.12323400e-17   1.00000000e+00]
112.5 	 [-0.38268343  0.92387953]
135.0 	 [-0.70710678  0.70710678]
157.5 	 [-0.92387953  0.38268343]
180.0 	 [ -1.00000000e+00   1.22464680e-16]
202.5 	 [-0.92387953 -0.38268343]
225.0 	 [-0.70710678 -0.70710678]
247.5 	 [-0.38268343 -0.92387953]
270.0 	 [ -1.83697020e-16  -1.00000000e+00]
292.5 	 [ 0.38268343 -0.92387953]
315.0 	 [ 0.70710678 -0.70710678]
337.5 	 [ 0.92387953 -0.38268343]
360.0 	 [  1.00000000e+00  -2.44929360e-16]
